server:
  port: 8084
spring:
  profiles: dev
  rabbitmq:
    endpoint: amqp://rabbit_user:rabbit_password@localhost:5672/myvhost
    exchange: your_exchange_name
    queue: your_queue_name
    gatewayId: your_gateway_id